import Head from 'next/head'
import { GameLayout } from './layouts/GameLayout.jsx'
import { Game } from '@/components/game/index.js';

const HomePage =  () => {
  return (
    <>
      <Head>
        <title>Memory tile game</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameLayout>
        <div className="container mx-auto px-4">
          <i className="fa-solid fa-house"></i>
          <Game></Game>
        </div>
      </GameLayout>
    </>
  )
}
export default HomePage;